// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: exchange.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MatchingEngineClient is the client API for MatchingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchingEngineClient interface {
	MatchOrder(ctx context.Context, in *OrderMessage, opts ...grpc.CallOption) (*MatchResponse, error)
	CancelOrder(ctx context.Context, in *CancelMessage, opts ...grpc.CallOption) (*CancelResponse, error)
}

type matchingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingEngineClient(cc grpc.ClientConnInterface) MatchingEngineClient {
	return &matchingEngineClient{cc}
}

func (c *matchingEngineClient) MatchOrder(ctx context.Context, in *OrderMessage, opts ...grpc.CallOption) (*MatchResponse, error) {
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, "/exchange.MatchingEngine/MatchOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) CancelOrder(ctx context.Context, in *CancelMessage, opts ...grpc.CallOption) (*CancelResponse, error) {
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, "/exchange.MatchingEngine/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingEngineServer is the server API for MatchingEngine service.
// All implementations must embed UnimplementedMatchingEngineServer
// for forward compatibility
type MatchingEngineServer interface {
	MatchOrder(context.Context, *OrderMessage) (*MatchResponse, error)
	CancelOrder(context.Context, *CancelMessage) (*CancelResponse, error)
	mustEmbedUnimplementedMatchingEngineServer()
}

// UnimplementedMatchingEngineServer must be embedded to have forward compatible implementations.
type UnimplementedMatchingEngineServer struct {
}

func (UnimplementedMatchingEngineServer) MatchOrder(context.Context, *OrderMessage) (*MatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MatchOrder not implemented")
}
func (UnimplementedMatchingEngineServer) CancelOrder(context.Context, *CancelMessage) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMatchingEngineServer) mustEmbedUnimplementedMatchingEngineServer() {}

// UnsafeMatchingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingEngineServer will
// result in compilation errors.
type UnsafeMatchingEngineServer interface {
	mustEmbedUnimplementedMatchingEngineServer()
}

func RegisterMatchingEngineServer(s grpc.ServiceRegistrar, srv MatchingEngineServer) {
	s.RegisterService(&MatchingEngine_ServiceDesc, srv)
}

func _MatchingEngine_MatchOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).MatchOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exchange.MatchingEngine/MatchOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).MatchOrder(ctx, req.(*OrderMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exchange.MatchingEngine/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).CancelOrder(ctx, req.(*CancelMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingEngine_ServiceDesc is the grpc.ServiceDesc for MatchingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.MatchingEngine",
	HandlerType: (*MatchingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MatchOrder",
			Handler:    _MatchingEngine_MatchOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MatchingEngine_CancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange.proto",
}
